sphere_option = ["Software Development",
    "Data Science","CTF","Cloud Computing","GameDev",
    "Iot","Blockchain/Crypto","QA","Networking", "UI/UX",
    "SysAdmin","Project Management"]
sphere_callback = ["SoftDev",
    "DataScience","CTF","CloudComputing","GameDev",
    "Iot","Blockchain/Crypto","QA","Networking", "UI/UX",
    "SysAdmin","ProjectManagement"]
subsphere = ["python javascript java c_sharp c_plus_plus c go golang rust kotlin swift typescript php ruby r scala perl dart haskell elixir erlang ocaml f_sharp clojure lua julia bash powershell sql t_sql pl_sql graphql vba matlab sas labview abap cobol fortran ada prolog lisp scheme verilog vhdl solidity vyper move cairo kotlin_android swift_ios dart_flutter react_native embedded_c assembly x86 arm html5 css3 sass scss less tailwind_css bootstrap material_ui chakra_ui ant_design bulma foundation react angular vue svelte next nuxt gatsby astro remix solid alpine jquery redux zustand mobx ngrx vuex pinia canvas_api webgl three d3 gsap framer_motion node express nest fastify django flask fastapi spring_boot micronaut quarkus laravel symfony ruby_on_rails phoenix asp_net_core gin rest graphql grpc websocket webrtc soap oauth_2 jwt nginx apache caddy traefik react_native flutter xamarin kotlin_multiplatform capacitor android kotlin java jetpack_compose ios swift objective_c swiftui uikit appium espresso xctest firebase_test_lab mysql postgresql oracle microsoft_sql_server sqlite mariadb cockroachdb mongodb redis cassandra dynamodb firebase_realtime_db neo4j arangodb couchdb elasticsearch hadoop spark hive hbase clickhouse snowflake bigquery docker kubernetes podman openshift helm nomad terraform pulumi ansible puppet chef saltstack jenkins github_actions gitlab_ci_cd circleci argocd tekton travis_ci prometheus grafana elk_stack elasticsearch logstash kibana loki splunk datadog new_relic zabbix nagios aws ec2 s3 lambda rds eks cloudformation azure vms blob_storage functions aks gcp compute_engine cloud_storage cloud_run gke digitalocean heroku vercel netlify firebase python pandas numpy r tidyverse sql excel power_query matplotlib seaborn plotly tableau power_bi looker metabase scikit_learn tensorflow pytorch keras xgboost lightgbm catboost nltk spacy hugging_face bert gpt langchain llamaindex apache_spark airflow kafka flink beam databricks selenium cypress playwright puppeteer jest mocha pytest junit jmeter locust gatling k6 owasp_zap burp_suite metasploit nmap kali_linux wireshark ssl tls aes rsa pki hashicorp_vault splunk qradar graylog wazuh gdpr pci_dss iso_27001 nist hipaa unity unreal_engine godot cryengine gamemaker phaser three webgl opengl directx vulkan arduino raspberry_pi esp32 stm32 freertos embedded_linux ros robot_os solidity ethereum hyperledger polkadot cosmos solana near algorand ipfs filecoin english intermediate advanced german french spanish chinese mandarin japanese higher_education computer_science applied_mathematics bootcamps le_wagon codeworks aws_certified azure_certified google_cloud_certified cka ckad docker_certified cissp ceh oscp google_data_analytics tensorflow_developer pmp csm teamwork adaptability critical_thinking time_management presentation_skills agile scrum kanban leadership"]
